### ISSUE TITLE
Unable to connect HA, but app working fine

### ISSUE THREAD

**Issue by tekhiegit** [kaotix/clevererspa#1]
Hi during the middle of the night HA dropped the connection to CleverSpa and I can't get it to reconnect, even removed and re-added the integration. Mostly just wondered if it was just me 🤷...

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/clevererspa/__init__.py:71
Integration: ClevererSpa
First occurred: 10:26:35 (2 occurrences)
Last logged: 13:19:17

Error setting up entry [email address redacted] for clevererspa
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/clevererspa/__init__.py", line 71, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, _PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by kaotix** [comment]
Hi, I don't currently have my Cleverspa in operation so I'm unable to test what could be going on. Has there been any app updates from Cleverspa lately? I'm wondering if they've altered their API or something and it's now broken the integration.

**Comment by tekhiegit** [comment]
Doesn't look like there's been any update to the so since August last year. I tried a password reset and it's the same, looks like the log in works in HA, but the error comes when trying to pull any data. Very odd. I guess next step is to delete and reconnect the hottub to the app/server and see if that makes a difference.

**Comment by kaotix** [comment]
Ok cool, keep me informed if you can. I'm probably due to get my hot tub back out soon so hopefully I can rejoin the effort to diagnose this if I experience the same issue.

**Comment by tekhiegit** [comment]
So looking back through the logs, I think that I may have lost connection and the ability to reconnect right after performing the 2023.5 update. I'd been holding off so went right to 2023.5.2 I wonder if it might have had some breaking changes that broke your integration.

**Comment by kaotix** [comment]
Thanks for the info, my main install is still on 2023.4.6 so it might still be working for me I also have a test install that's on the absolute latest so I can see what it does on that.

**Comment by tekhiegit** [comment]
So found the fix by searching for the error message that was showing up. So it was a really easy fix, just a single line in the "__init__.py" file.

Line 71 just needed to be changed from...
hass.config_entries.async_setup_platforms(entry, _PLATFORMS)

to...
await hass.config_entries.async_forward_entry_setups(entry, _PLATFORMS)

I guess that some changes were made to the last major update, don't know why this fixes it, but it seems to be all fine now.

**Comment by alastairg100** [comment]
Hi, I'm brand new to this. Where would I find the init.py file to edit it as you have above? I am getting the same error log.
Thanks

**Comment by kaotix** [comment]
I've just pushed the fix for this directly thanks to @tekhiegit 
If you update now you should have the latest init.py

#https://github.com/kaotix/clevererspa/commit/9b8d4e22662b45e7aa8ae8157030da521cb16e79

**Comment by kaotix** [comment]
@tekhiegit is your control still working? And the actual app itself? Mine have both recently stopped working for control. They will report the information it currently has set but I can't control anything.

**Comment by tekhiegit** [comment]
> @tekhiegit is your control still working? And the actual app itself? Mine have both recently stopped working for control. They will report the information it currently has set but I can't control anything.

Tbh it's a bit hit and miss at the moment, generally works though. Sometimes it looks like it's not working, but when I go to the tub is all fine. In fact HA is usually correct even when the official app is not.

**Comment by kaotix** [comment]
Turns out it was the filter code stopping it from turning on the pump. But it didn't tell me anywhere other than on hot tub itself. I'm working on some updates to this code to make it a bit more responsive but I agree I think this works better than the native app.
Also I'm not sure how long everything will stay working with the company gone out of business so I'm working on something for that too.

**Comment by tekhiegit** [comment]
Had no idea they'd gone out of business. Still selling them around here

**Comment by kaotix** [comment]
Yeh they're selling them in the shops, I don't know if their business got bought out or what but CleverSpa themselves went into administration last October.
My concern is parts availability and warranty cover as I've only had mine 12 months so I just hope nothing goes wrong with it.

**Comment by tekhiegit** [comment]
Yeah, just been reading about it. Can't see that they were bought, but you'd think that hot tub companies would have realised that the massively increased sales during lockdown weren't going to continue afterwards, but I guess no one really saw the energy cost issues

**Comment by kaotix** [comment]
My biggest concern honestly is if the app/API stops working because then I'll need to go outside to the hot tub to control it like a neanderthal. That's why I'm working on a solution to that.
Thankfully the controls run on a separate PCB with an ESP8266 on-board from what I can tell. I have said board (spare) and have started digging into it in the hopes I can offer a hardware flashed fix for it.

**Comment by alastairg100** [comment]
B&Q still sell filter and chlorine etc. 

weirdly my app still works. Your integration Kaotix still works if you operate it manually. What doesn’t seem to trigger is my automations for when my solar panels are exporting but they have been for the last two weeks.

**Comment by kaotix** [comment]
Consumables will work for any tub, that's another thing though the filters will eventually disappear I'm sure. I don't think they're the same as Lay-Z-Spa filters. Can probably 3D print an adapter though.

Do you have any traces from your automation to suggest why they're not triggering? I have a few automations that work fine with my integration actually. Nothing solar related but I guess the theory is the same. Just triggering either the heater on or off mainly based on temperatures.

**Comment by alastairg100** [comment]
Sorry, my fault. Turns out it’s at the Growatt (solar inverter) end. All variables there are down as unavailable, so nothing is being read to trigger my automations
